query CodeFrame {
  codeframe_check_report {
    ObjectID
    LocalID
    ObjectType
    TestItem {
      TestItemContent {
        ItemSubstitutedForList {
          SubstituteItem {
            SubstituteItemRefId
            LocalId
          }
        }
      }
    }
  }
}

