query NAPTestAttempts($acaraIDs: [String]) {
  domain_scores_event_report_by_school(acaraIDs: $acaraIDs) {
    Event {
       ParticipationCode
    }
    Test {
      TestContent {
        TestLevel
        TestDomain
      }
    }
  }
}

