query NAPDomainScores($acaraIDs: [String]) {
  student_event_acara_id_discrepancy_by_school(acaraIDs: $acaraIDs) {
    Student {
      FamilyName
      GivenName
      TestLevel
      YearLevel
      BirthDate
      ASLSchoolId
      OtherIdList {
        OtherId {
          Type
          Value
        }
      }
    }
    Event {
      SchoolID
      NAPTestLocalID
    }
  }
}

