query NAPParticipation($acaraIDs: [String]) {
  participation_report_by_school(acaraIDs: $acaraIDs) {
    Student {
      BirthDate
      Sex
      IndigenousStatus
      LBOTE
      YearLevel
      ASLSchoolId
      HomeSchooledStudent
      Parent1SchoolEducation
      Parent1NonSchoolEducation
      Parent1Occupation
      Parent2SchoolEducation
      Parent2NonSchoolEducation
      Parent2Occupation
      OtherIdList {
        OtherId {
          Type
          Value
        }
      }
    }
    School {
      SchoolName
      SchoolGeographicLocation
      SchoolSector
      SchoolContactList {
        SchoolContact {
          ContactInfo {
            Address {
              PostalCode
              StateProvince
              City
            }
          }
        }
      }
    }
    Summary {
      Domain
      ParticipationCode
    }
  }
}
