query NAPParticipation($acaraIDs: [String]) {
  participation_report_by_school(acaraIDs: $acaraIDs)
  {
    Summary {
      Domain
      ParticipationCode
    }
    EventInfos{
      Event{
        TestDisruptionList{
          TestDisruption {
            Event
          }
        }
      }
    }
  }
}

