query NAPDomainScores($acaraIDs: [String]) {
  item_counts(acaraIDs: $acaraIDs) {
    TestName
    TestLevel
    TestDomain
    TestItemLocalId
    Substitute
    Codeframe
    Count
    SubstitutedItems
  }
}
