query NAPDomainScores($acaraIDs: [String]) {
  test_completeness_report(acaraIDs: $acaraIDs) {
    ACARAID
    TestDomain
    TestLevel
    P_Attempts_Count
    S_Attempts_Count
    Responses_Count
    Attempts_With_No_Response
    Responses_With_No_Attempt
  }
}
