query NAPDomainScores($acaraIDs: [String]) {
  domain_scores_event_report_by_school(acaraIDs: $acaraIDs) {
    Student {
      FamilyName
      GivenName
      BirthDate
      OtherIdList {
        OtherId {
          Type
          Value
        }
      }
    } 
    Test {
      TestContent {
        TestLevel
        TestDomain
      } 
    } 
    Event {
       ParticipationCode
    }
    Response {
       ResponseID
       PathTakenForDomain
       ParallelTest
       DomainScore {
         RawScore
       }
    }
    SchoolDetails {
      ACARAId
      SchoolName
    }
  }
}

