query TestTypeItemImpacts($acaraIDs: [String]) {
  test_type_item_impacts(acaraIDs: $acaraIDs) {
    TestName   
    TestLevel
    TestDomain


"Test Name","Test level","Test Domain","Test Item Local Id","Test Item Name","Subdomain","Writing Genre","Birth Date","ACARA ID","PSI","Testlet Score","Item Score","Item Lapsed Time","Item Subscores","Item Response","Participation Code","Error"



    Student {
      FamilyName
      GivenName
      BirthDate
      OtherIdList {
        OtherId {
          Type
          Value
        }
      }
    }
    Test {
      TestContent {
        TestLevel
        TestDomain
      }
    }
    Event {
       EventID
       ParticipationCode
       TestDisruptionList {
         TestDisruption {
           Event
         }
       }
    }
    Response {
       ResponseID
       PathTakenForDomain
       ParallelTest
       DomainScore {
         RawScore
       }
    }
    SchoolDetails {
      ACARAId
      SchoolName
    }
  }
}


