query NAPScoreSummaries($acaraIDs: [String]) {
  score_summary_report_by_school(acaraIDs: $acaraIDs){
    Summ {
      SchoolACARAId
      DomainNationalAverage
      DomainSchoolAverage
      DomainJurisdictionAverage
      DomainTopNational60Percent
      DomainBottomNational60Percent
    }
    Test {
      TestContent{
        TestName
      }
    }
  }
}

