query QLDstudents {
  students {
      FamilyName
      GivenName
      BirthDate
      Sex
      IndigenousStatus
      LBOTE
      YearLevel
      ASLSchoolId
      ClassGroup
      OtherIdList {
        OtherId {
          Type
          Value
        }
      }
  }
}
