query ScoreSummaries {
  score_summaries {
    SchoolACARAId
    NAPTestLocalId
    DomainNationalAverage
    DomainSchoolAverage
    DomainJurisdictionAverage
    DomainTopNational60Percent
    DomainBottomNational60Percent
  }
}

