query NAPParticipation($acaraIDs: [String]) {
  pnp_events_report(acaraIDs: $acaraIDs) {
        EventID
        PSI
        SchoolID
        NAPTestLocalID
        Adjustment {
          PNPCodelist {
            PNPCode
         }
       }
  }
}
