query NAPDomainScores($acaraIDs: [String]) {
  domain_scores_event_report_by_school(acaraIDs: $acaraIDs) {
    Test {
      TestContent {
        TestName
        TestLevel
        TestDomain
        TestYear
      }
    }
    SchoolDetails {
      SchoolName
      ACARAId
    }
    Student {
      FamilyName
      GivenName
      YearLevel
    }
    Event {
      ParticipationCode
    }
    Response {
      PSI
      ParallelTest
      DomainScore {
        RawScore
        ScaledScoreValue
        StudentDomainBand
        StudentProficiency
      }
    }
  }
}

