query ISRPrinting($acaraIDs: [String]) {
  isrReportItemsExpanded(acaraIDs: $acaraIDs) {
    Student {
        LocalId
        StateProvinceId
        OtherIdList
        FamilyName
        GivenName
        MiddleName
        PreferredName
        IndigenousStatus
        Sex
        BirthDate
        CountryOfBirth
        StudentLOTE
        VisaCode
        LBOTE
        AddressLine1
        AddressLine2
        Locality
        StateTerritory
        Postcode
        SchoolLocalId
        YearLevel
        FTE
        Parent1LOTE
        Parent2LOTE
        Parent1Occupation
        Parent2Occupation
        Parent1SchoolEducation
        Parent2SchoolEducation
        Parent1NonSchoolEducation
        Parent2NonSchoolEducation
        LocalCampusId
        ASLSchoolId
        TestLevel
        Homegroup
        ClassGroup
        MainSchoolFlag
        FFPOS
        ReportingSchoolId
        OtherSchoolId
        EducationSupport
        HomeSchooledStudent
        Sensitive
        OfflineDelivery
    }
    SchoolID
    SchoolName
    R_Score
    R_Mean
    R_Comment
    R_Participation
    R_Pathway
    R_Stddev
    W_Score
    W_Mean
    W_Comment
    W_Participation
    W_Pathway
    W_Stddev
    S_Score
    S_Mean
    S_Comment
    S_Participation
    S_Pathway
    S_Stddev
    G_Score
    G_Mean
    G_Comment
    G_Participation
    G_Pathway
    G_Stddev
    N_Score
    N_Mean
    N_Comment
    N_Participation
    N_Pathway
    N_Stddev
  }
}
