query NAPDataSchools {
  schools {
    RefId
    LocalId
    StateProvinceId
    ACARAId
    SchoolName
    SchoolDistrict
    SchoolType
    StudentCount
    SchoolURL
    SessionType
    ARIA
    OperationalStatus
    FederalElectorate
    SchoolSector
    IndependentSchool
    NonGovSystemicStatus
    System
    ReligiousAffiliation
    SchoolGeographicLocation
    LocalGovernmentArea
    JurisdictionLowerHouse
    SLA
    SchoolCoEdStatus
    PrincipalInfo {
      ContactTitle
      ContactName {
        Type
        Title
        FamilyName
        GivenName
        MiddleName
        Suffix
        FullName
      }
    }
  }
}
