query CodeFrame {
  testlets {
    TestletID
      NAPTestLocalId
      TestletContent {
        LocalId
          TestletName
          Node
          LocationInStage
          TestletMaximumScore
      }
  }
}



