query CodeFrame {
  tests {
    TestID
      TestContent {
        LocalId
          TestName
          TestLevel
          TestDomain
          TestYear
          StagesCount
          TestType
          DomainBands {
            Band1Lower
              Band1Upper
              Band2Lower
              Band2Upper
              Band3Lower
              Band3Upper
              Band4Lower
              Band4Upper
              Band5Lower
              Band5Upper
              Band6Lower
              Band6Upper
              Band7Lower
              Band7Upper
              Band8Lower
              Band8Upper
              Band9Lower
              Band9Upper
              Band10Lower
              Band10Upper
          }
        DomainProficiency {
          Level1Lower
            Level1Upper
            Level2Lower
            Level2Upper
            Level3Lower
            Level3Upper
            Level4Lower
            Level4Upper
        }
      }
  }
}



