query NAPDomainScores($acaraIDs: [String]) {
  domain_scores_report_by_school(acaraIDs: $acaraIDs) {
    Test {
      TestContent {
        TestName
        TestLevel
        TestDomain
        TestYear
      }
    }
    Response {
      PSI
      DomainScore {
        RawScore
        ScaledScoreValue
        ScaledScoreLogitValue
        ScaledScoreStandardError
        ScaledScoreLogitStandardError
        StudentDomainBand
        StudentProficiency
      }
    }
  }
}

