query ISRPrinting($acaraIDs: [String]) {
  isrReportItems(acaraIDs: $acaraIDs) {
    StudentLocalID
    StudentFirstName
    StudentLastName
    SchoolID
    SchoolName
    YearLevel
    R_Score
    R_Mean
    R_Comment
    W_Score
    W_Mean
    W_Comment
    S_Score
    S_Mean
    S_Comment
    G_Score
    G_Mean
    G_Comment
    N_Score
    N_Mean
    N_Comment
  }
}
